### ISSUE TITLE
Storyline

### ISSUE THREAD

**Issue by why1998101** [cs130-w21/6#1]
## Epic
Description and User Benefit:
Besides the Image Upload page which contains our core feature, MyStory has a Storyline page where the personal history of a user's Image Upload is displayed. This page could benefit users in that they could have an idea of their past experience and it could be used as many things for example a photo album.

User Actions:

- The user should be able to view his/her storyline once shifting to the Storyline page.
- The user should be able to delete his/her past stories.

## User Stories
- [x] View storyline #8 
- [x] Delete a past story #9 
- [x] Python server: communicate between the frontend, serving Tensorflow, and database #10 
- [x] Database: store user information and storylines #6
