### ISSUE TITLE
Python server

### ISSUE THREAD

**Issue by yiyou-chen** [cs130-w21/6#10]
## User Story
As a **Python Server**, I would like **receive data and save it to the database or run TensorFlow**.

## Acceptance Criteria
- [x] Given **'upload' with user id and image data**, then **call TensorFlow with image data, send back 'upload' + caption data via socket** #31 
- [x] Given **'login' and user ID, password**, then **send 'login' + success/fail** #32 
- [x] Given **'load' and user ID**then **request all row id, image and caption info with user ID from the database, and send back 'load' + image and caption data via socket** #33 
- [x] Given **'register', user ID, Password, Email**, then **save info to User Table, and send back 'register' + success/fail via socket** #35 
- [x] Given **'confirm' + User ID + image + confirmed caption**, then **save the image to disk. add user id, image directory, confirmed caption, data/time, validness to database, send back 'confirm' + row id in Image Table** #34 
- [x] Given **'delete' +  row id of image**, then **mark corresponding validness=0 in Image Table, send back 'delete' + success/fail**. #36

**Comment by yiyou-chen** [comment]
Done
