### ISSUE TITLE
Story Upload

### ISSUE THREAD

**Issue by why1998101** [cs130-w21/6#11]
## Epic
Description and User Benefit:
MyStory is an AI-driven mobile app capable of suggesting quotes for user-input images. Story Upload is the core feature that accepts a user input image and returns several options of text. This feature could typically benefit users who want to upload an image to the social network with no idea of the corresponding text. Meanwhile, this feature could also be more widely used to get information from an image.

User Actions:

- The user should be able to upload an existing picture from his/her device.
- The user should be able to use the device camera to take a picture inside the application.
- The user should be able to see the quote suggestions for the uploaded images.
- The user should be able to edit the quote suggestions and confirm a story to be created.

## User Stories
- [x] Take a picture, upload and check result #3 
- [x] Choose a image , upload and check result #2
- [x] Edit and confirm a suggested quote #4 
- [x] Python server: communicate between the frontend, serving Tensorflow, and database #10 
- [x] Serving Tensorflow: implement an encoder-decoder model for Image-to-Text conversion #7
