### ISSUE TITLE
App Homepage

### ISSUE THREAD

**Issue by XintaY** [cs130-w21/6#15]
## User Story
As a user, I would like an instructive app home screen so that I can start recording my stories.

## Detailed Description
The home screen contains the camera button which allows user to upload photos to our backend server. Also, a user is able to login to his/her account where his/her past photo stories are stored. In addition, there is a registration button on our app home screen. Finally, on top of the app home screen, there is a display of weather info at the user's current location.

## Acceptance Criteria
- [x] Given **[click on camera button]**, then **[user can choose either to upload via phone library or use phone camera]** #17 
- [x] Given **[input username and password and click on LOG-IN button]**, then **[user's input is recorded]** #18 
- [x] Given **[click on REGISTER button]**, then **[user navigates to registration page]** #19
