### ISSUE TITLE
Choose a local image and upload

### ISSUE THREAD

**Issue by yzchen99** [cs130-w21/6#2]
## User Story
As a user, I would like to upload an image from my local device so that I can add it to my storyline and get a suggested quote.
## Detailed Description
The user's click on a button should trigger a device file explorer. Android Studio should send the image to the Python server through a socket and wait for a response from the server.
## Acceptance Criteria
- [x] Given a button click, then able to choose photo from phone gallery. #20 
- [x] Given a valid image input, then let the user crop the image to square size and send the cropped image to Python server via socket. #21 
- [x] Given a valid image from user, then user can choose to either type his/her quote, or choose to obtain a quote from our server (which can then further edit it). #22 
- [x] Given the valid image and quote, then user can upload the tuple to our server. #23
