### ISSUE TITLE
Take a picture and upload

### ISSUE THREAD

**Issue by yzchen99** [cs130-w21/6#3]
## User Story
As a user, I would like to take a picture from my camera so that I can add it to my storyline and get a suggested quote.

## Detailed Description
The user's click on a button should trigger the front camera. Android Studio should send the image to the Python server through a socket and wait for a response from the server.

## Acceptance Criteria
- [x] Given user's choice to use camera, then the front camera open. #24 
- [x] Given a photo, then let the user crop the image to square size and send the cropped image to Python server via socket. #25 
- [x] Given the valid photo, then user see the result of suggested quote (or his/her own quote) displayed on the same page.  #26 
- [x] Given the valid photo and quote, then user is able to upload the tuple to our server. #27
