### ISSUE TITLE
Register and Log-in

### ISSUE THREAD

**Issue by yzchen99** [cs130-w21/6#5]
## User Story
As a user, I would like to register for an account so that I can access MyStory.
As a user, I would like to log in to my account so that I can view my stories.
As a user, I would like to log out of my account when I am not active. 
## Detailed Description
Registration requires a new user to provide a unique user_id and password. The user_id and password pair will be sent to the Python server and saved in a user information table in the database.
After registration, the user can log in using his/her user_id and password. Every time the user tries to log in, his/her user_id and password will be verified first before access to MyStory.
The user can log out with a button if want to.
## Acceptance Criteria
- [x] Given a user switch to the register page, then the register page shows up which asks the user to enter information. #37 
- [x] Given a user entering an existing user_id during registration, then an error message will be printed on the registration screen. #38 
- [x] Given a user successfully registering an account, then the app automatically navigates to this new user's story-line screen #39 
- [x] Given a user entering an incorrect user_id, password pair during login, then an error message will be printed on the registration/login screen. #40 
- [x] Given a user entering a correct user_id, password pair during login, then the screen will jump to the story-line page.  #41
